#!/usr/bin/env bash

for project in */log
do
  if [ "$project" == "*/log" ]; then
    echo "Nothing to do"
    break
  fi
  if [ ! -e $project ]; then
    rm $project
  else
    rm -rf $project
  fi
  echo "creating /tmp/$project"
  if [ ! -d /tmp/$project ]; then
    mkdir -p /tmp/$project
  fi
  ln -s /tmp/$project $project
done
